server:
  port: 9003
  shutdown: graceful

spring:
  application:
    name: shipping-service
  profiles:
    active: local

  cloud:
    config:
      enabled: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # Kafka 클러스터에 대한 초기 연결에 사용할 호스트:포트
      topic: shipping-save
      group-id: shipping # Consumer는 Consumer Group이 존재하기 때문에, 유일하게 식별 가능한 Consumer Group을 작성합니다.
      auto-offset-reset: earliest # Kafka 서버에 초기 offset이 없거나, 서버에 현재 offset이 더 이상 없는 경우 수행할 작업을 작성합니다.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false